tags:
- name: Token Generator
  description: This project is a personnal utils to generate token with smart contract ERC721 / ERC1155 / ERC20.

paths:
# [POST] tokens
    post:
      tags:
      - tokens
      summary: Generate json tokens
      parameters:
      - name: body
        in: body
        description: token Data
        required: true
        schema:
          $ref: '#/definitions/tokens'
      responses:
        201:
          description: 'Generated'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [POST] tokens
    post:
      tags:
      - tokens
      summary: Generate zip tokens
      parameters:
      - name: body
        in: body
        description: token Data
        required: true
        schema:
          $ref: '#/definitions/tokens'
      responses:
        201:
          description: 'Generated'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  tokens:
    type: object
    required:
        - name
        - description
        - image
        - edition
        - collection
        - symbol
        - properties
        - category
        - creators
        - attributes
    properties:
      name:
        type: string
        description: name of token
      description:
        type: string
        description: description of token
      image:
        type: string
        description: image uri of token
      edition:
        type: string
        description: edition of token
      collection:
        type: Object
        description: collection of token
      symbol:
        type: string
        description: symbol of token
      properties:
        type: Object
        description: symbol of token
      category:
        type: string
        description: category of token
      creators:
        type: string
        description: creators of token
      attributes:
        type: Object
        description: attributes of token

schemes:
 - https
 - http
